Refactore generate_sighash_all
nervosnetwork/ckb-auth pull request #22
Opened 2023-11-20 09:51 UTC by joii2020

* Merge CkbAuthError and CkbAuthTypesError (Solve the dependency of generate_sighash_all)
* generate_sighash_all move to ckb-auth-rs

2023-11-21 05:09 UTC, quake commented on examples/auth-rust-demo/contracts/auth-rust-demo/src/entry.rs
> +    ckb_auth::{ckb_auth, CkbEntryType},
suggest to change `pub use ckb_auth::ckb_auth` and move `CkbEntryType` to lib.rs, then user may use it directly:

```
use ckb_auth_rs::{ckb_auth, CkbEntryType, CkbAuthType, ... }
```

and no need to define dummy `CkbEntryType` type in the unit test:
https://github.com/nervosnetwork/ckb-auth/blob/main/examples/auth-rust-demo/tests/src/tests.rs#L38-L42

2023-11-23 06:43 UTC, XuJiandong approved these changes

2023-11-23 06:59 UTC, XuJiandong requested changes

2023-11-23 06:59 UTC, XuJiandong commented on ckb-auth-rs/src/lib.rs
> +#[cfg(target_arch = "riscv64")]
duplicated.

2023-11-23 06:59 UTC, XuJiandong commented on ckb-auth-rs/src/lib.rs
> +    UnknowAlgorithmID,
typo

2023-11-23 07:22 UTC, XuJiandong approved these changes

2023-11-23 07:22 UTC, merged